// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	time "time"
	mock "github.com/stretchr/testify/mock"
)

// SystemLibraryProvider is an autogenerated mock type for the SystemLibraryProvider type
type SystemLibraryProvider struct {
	mock.Mock
}

// Chdir provides a mock function with given fields: dir
func (_m *SystemLibraryProvider) Chdir(dir string) error {
	ret := _m.Called(dir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sleep provides a mock function with given fields: d
func (_m *SystemLibraryProvider) Sleep(d time.Duration) {
	_m.Called(d)
}
